// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SManagement.DataAccess;

namespace SManagement.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220707144958_SeedStafTable")]
    partial class SeedStafTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SManagement.Models.Staf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Stafs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 1,
                            Email = "tohirbekarzimurodov@gmail.com",
                            FirstName = "Tohir",
                            LastName = "Arzimurodov"
                        },
                        new
                        {
                            Id = 2,
                            Department = 1,
                            Email = "tohirbekarzimurodov@gmail.com",
                            FirstName = "Tohirbe",
                            LastName = "Arzimurodov"
                        },
                        new
                        {
                            Id = 3,
                            Department = 1,
                            Email = "tohirbekarzimurodov@gmail.com",
                            FirstName = "Tohirbek",
                            LastName = "Arzimurodov"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
